pipelines:
  default:
  - step:
      name: 'Build PDF'
      script:
        - docker run --rm -v $PWD/latex:/data alecci/xelatex:latest
        - curl -X POST "https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"latex/oauth2.pdf"
      services:
        - docker
      caches:
        - docker
