version: '3'

services:
  notebook:
    build: ./notebook
    ports:
      - 3333:3333

    volumes:
      - ./notebook/OAuth2-presentation.ipynb:/notebook/OAuth2-presentation.ipynb

  server:
    build: ./server
    ports:
      - 8080:8080
    environment:
      PORT: 8080

  xelatex:
    build: ./latex
    volumes:
      - ./res/:/res
      - ./latex/oauth2.tex/:/latex/oauth2.tex
