version: '3'

services:
  notebook:
    build:
      dockerfile: ./Dockerfile.notebook
      context: .
    ports:
      - 3333:3333

    volumes:
      - ./OAuth2-presentation.ipynb:/notebook/OAuth2-presentation.ipynb
