version: '3'

services:
  notebook:
    build: ./notebook
    ports:
      - 8000:8000
      - 3333:3333
    env_file:
      - .env

    volumes:
      - ./notebook/OAuth2-presentation.ipynb:/notebook/OAuth2-presentation.ipynb

  xelatex:
    build: ./latex
    volumes:
      - ./res/:/res
      - ./latex/oauth2.tex/:/latex/oauth2.tex
