# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    branches: [master]
  workflow_dispatch:


jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1

      - name: Build PDF
        run: docker run -v $PWD/latex:/data alecci/xelatex:latest
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tesi_oauth.pdf
          path: latex/oauth2.pdf
   
